### PR TITLE
Adding the etcdctl aliases for 2.3 and 3.0 channels.

### PR DESCRIPTION
**Pull request by mbruzek**
We got a request for the etcdctl alias in the 2.3 etcd snap channel.

https://github.com/juju-solutions/layer-etcd/issues/92

### CODE REVIEW

**Comment by lazypower** [comment]
These changes are +1 LGTM. 

This should resolve any confusion stemming from the command change when switching to snaps from the deb packaging.  Thanks for the submission @mbruzek

**Comment by lazypower** [comment]
bump on this issue for visibility. cc @markshuttle

**Comment by markshuttle** [comment]
Ah, I need to add the alias bits to the snap for all tracks, will do.

Mark

**Comment by markshuttle** [comment]
OK, 2.3.8 with alias for etcdctl now in 2.3/candidate pls validate and
reply.

Mark

**Comment by lazypower** [comment]
I can confirm that what's in 2.3/candidate setup the alias we expected. 

Was that built/released with this PR? I was a bit startled to see the effect land before the code did, but aside from that, testing was positive.

**Comment by markshuttle** [comment]
On 25/04/17 19:20, Charles Butler wrote:
> Was that built/released with this PR? I was a bit startled to see the
> effect land before the code did, but aside from that, testing was
> positive.

No, it was a one-line cut and paste from one snapcraft.yaml to another,
I just did it and pushed. Will release to stable now.

Mark

**Comment by mbruzek** [comment]
Not needed any longer

**Pull request closed without merging**
